#!/usr/bin/env bash
# Idempotent repository bootstrap for Agent C Cloud Agents.
# Runs after the repo is checked out. Safe to run repeatedly.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

echo "==> Installing dependencies (pnpm)"
corepack enable >/dev/null 2>&1 || true
pnpm install --frozen-lockfile

echo "==> Starting PostgreSQL to apply migrations"
pg_ctlcluster 16 main start 2>/dev/null || true
for _ in $(seq 1 30); do
  if pg_isready -h 127.0.0.1 -p 5432 >/dev/null 2>&1; then break; fi
  sleep 1
done
pg_isready -h 127.0.0.1 -p 5432

echo "==> Ensuring local 'postgres' role password"
su - postgres -c "psql -v ON_ERROR_STOP=1 -c \"ALTER USER postgres PASSWORD 'postgres';\""

if [ ! -f .env.local ]; then
  echo "==> Generating .env.local (local dev secrets + local Postgres)"
  BETTER_AUTH_SECRET="$(node -e "console.log(require('crypto').randomBytes(32).toString('base64'))")"
  INTERNAL_API_SECRET="$(node -e "console.log(require('crypto').randomBytes(32).toString('base64'))")"
  FLAGS_SECRET="$(node -e "console.log(require('crypto').randomBytes(32).toString('base64url'))")"
  cat > .env.local <<EOF
# Local development env — generated by .cursor/install.sh. Do not commit.
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
BETTER_AUTH_URL=http://localhost:3000

INTERNAL_API_SECRET=${INTERNAL_API_SECRET}

# Local PostgreSQL 16 provided by the Cloud Agent image.
DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:5432/postgres
DIRECT_URL=postgresql://postgres:postgres@127.0.0.1:5432/postgres

FLAGS_SECRET=${FLAGS_SECRET}

# Google Workspace OAuth (web only). Sign-in needs real GCP OAuth credentials;
# provide them as Cloud Agent secrets when end-to-end login is required.
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_WORKSPACE_DOMAIN=
EOF
fi

echo "==> Applying Drizzle migrations"
set -a
# shellcheck disable=SC1091
. ./.env.local
set +a
pnpm db:migrate

echo "==> Applying hand-written supabase/migrations (idempotent)"
for f in supabase/migrations/*.sql; do
  [ -e "$f" ] || continue
  echo "    - $f"
  psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$f"
done

echo "==> install.sh complete"
